refactor(install): cleaned up scripts, more flexibility

diff --git a/acdc b/acdc
--- a/acdc
+++ b/acdc
@@ -1,17 +1,43 @@
 #!/bin/bash
 
+
+# Config
+
+PREFIX='@_PREFIX_@'
+USE_BIN='@_USE_BIN_@'
+GIT_UPSTREAM_URL='@_GIT_UPSTREAM_URL_@'
+
+if [ -z "$LOCAL_PREFIX" ]
+then
+	LOCAL_PREFIX=@_DEFAULT_LOCAL_PREFIX_@
+fi
+
+if [ -z "$DATA_DIR" ]
+then
+	DATA_DIR=@_DEFAULT_DATA_DIR_@
+fi
+
+
+# Other constants
+
 PYTHON_VERSION=3.6.9
-DATA_DIR=@_DATA_DIR_@
-PYENV_ROOT="$HOME/.pyenv"
-PATH="$PYENV_ROOT/versions/$PYTHON_VERSION/bin:$HOME/.local/bin:$PATH"
-INSTALL_DIR="@_INSTALL_DIR_@"
+INSTALL_DIR="$PREFIX/share/acdc-toolkit"
+
+export PYENV_ROOT="$HOME/.pyenv"
+if ! [ -d "$PYENV_ROOT" ]
+then
+	PYENV_ROOT="$LOCAL_PREFIX/share/pyenv"
+fi
+
+export WORKON_HOME="$LOCAL_PREFIX/share/virtualenvs"
+
+PATH="$PYENV_ROOT/versions/$PYTHON_VERSION/bin:$LOCAL_PREFIX/bin:$PATH:$PYENV_ROOT/bin"
+
+export PYTHONUSERBASE="$LOCAL_PREFIX"
+
+#
 
 cd "$INSTALL_DIR"
-
-if ! which pyenv > /dev/null 2> /dev/null
-then
-	PATH="$PATH:$PYENV_ROOT/bin"
-fi
 
 function confirm()
 {
@@ -21,8 +47,94 @@ function confirm()
 	return $?
 }
 
-function update_pipenv()
+function maybe_sudo()
 {
+	"$@" 2> /dev/null || sudo "$@"
+	return $?
+}
+
+if [ $# -eq 1 ] && [ "$1" = 'uninstall' ]
+then
+	rm -f "$DATA_DIR/.installed"
+
+	# User components
+
+	pipenv --rm
+
+	if confirm 'Remove local data'
+	then
+		rm -rf "$DATA_DIR/"
+	fi
+
+	if [ "$(which pyenv 2> /dev/null)" = "$PYENV_ROOT/bin/pyenv" ] && confirm 'Uninstall pyenv'
+	then
+		rm -rf "$PYENV_ROOT/"
+	fi
+
+	if [ "$(which pipenv 2> /dev/null)" = "$LOCAL_PREFIX/bin/pipenv" ] && confirm 'Uninstall pipenv'
+	then
+	    pip3 uninstall pipenv
+	fi
+
+	# Global components
+
+	cd /
+	maybe_sudo rm -rf "$INSTALL_DIR"
+	maybe_sudo rm -f "$BASH_SOURCE"
+elif [ $# -eq 1 ] && [ "$1" = 'update' ]
+then
+	if [ -z "$GIT_UPSTREAM_URL" ]
+	then
+		echo "The program doesn't seem to have been installed from git." >&2
+		echo "Maybe update it using your package manager." >&2
+		exit 1
+	fi
+
+	# Getting new sources
+
+	DL_DIR="$(mktemp -d 2>/dev/null || mktemp -d -t 'acdc-toolkit-dl')"
+	git clone "$GIT_UPSTREAM_URL" "$DL_DIR" || exit 1
+	cd "$DL_DIR"
+
+	# Removing old installation
+
+	NONCE=1
+	while [ -e "$INSTALL_DIR.backup.$NONCE" ]
+	do
+		((NONCE++))
+	done
+	INSTALL_DIR_BACKUP="$INSTALL_DIR.backup.$NONCE"
+	maybe_sudo mv "$INSTALL_DIR" "$INSTALL_DIR_BACKUP" || exit 1
+
+	# Reinstalling
+
+	INTERACTIVE=false \
+			   PREFIX='@_PREFIX_@' \
+			   USE_BIN='@_USE_BIN_@' \
+			   GIT_UPSTREAM_URL='@_GIT_UPSTREAM_URL_@' \
+			   DEFAULT_LOCAL_PREFIX='@_DEFAULT_LOCAL_PREFIX_@' \
+			   DEFAULT_DATA_DIR='@_DEFAULT_DATA_DIR_@' \
+			   ./install
+
+	STATUS=$?
+	if [ $STATUS -ne 0 ]
+	then
+		echo 'Failed to install new version. Restoring old one.' >&2
+		maybe_sudo rm -rf "$INSTALL_DIR"
+		maybe_sudo mv "$INSTALL_DIR_BACKUP" "$INSTALL_DIR"
+	else
+		maybe_sudo rm -rf "$INSTALL_DIR_BACKUP"
+	fi
+
+	# Cleanup
+
+	cd ..
+	rm -rf "$DL_DIR"
+
+	# All done
+
+	exit $STATUS
+else
 	REQUIRED="$(shasum Pipfile.lock | sed 's/\s.*//')"
 	INSTALLED="$(cat "$DATA_DIR/.installed" 2> /dev/null)"
 
@@ -49,41 +161,6 @@ function update_pipenv()
 		echo 'Hint: You can uninstall this program from your user directory'
 		echo 'by running "'"$0"' uninstall".'
 	fi
-}
 
-if [ $# -eq 1 ] && [ "$1" = 'uninstall' ]
-then
-	rm -f "$DATA_DIR/.installed"
-	pipenv --rm
-
-	if confirm 'Remove local data'
-	then
-		rm -rf "$DATA_DIR/"
-	fi
-
-	if [ -d "$PYENV_ROOT" ] && confirm 'Uninstall pyenv'
-	then
-		rm -rf "$PYENV_ROOT/"
-	fi
-
-	if [ "$(which pipenv 2> /dev/null)" = "$HOME/.local/bin/pipenv" ] && confirm 'Uninstall pipenv'
-	then
-	    pip3 uninstall pipenv
-	fi
-
-	if [ "$(stat -c '%U' .)" = "$USER" ]
-	then
-		echo 'Uninstalling...'
-		INSTALL_DIR="$(pwd)"
-		cd ..
-		rm -r "$INSTALL_DIR"
-		echo "All done."
-	else
-		echo
-		echo "Notice: Your user directory has been cleaned, but the program is"
-		echo "still installed system-wide."
-	fi
-else
-	update_pipenv
-	pipenv run ./toolkit.py "$@"
+	ACDC_DATA_DIR="$DATA_DIR" pipenv run ./toolkit.py "$@"
 fi
diff --git a/install b/install
--- a/install
+++ b/install
@@ -13,48 +13,73 @@ ask_string()
 	fi
 }
 
+maybe_sudo()
+{
+	"$@" 2> /dev/null || sudo "$@"
+	return $?
+}
 
-# CONFIG
 
+# Config
 
 if [ "$INTERACTIVE" = false ]
 then
 	PREFIX="${PREFIX:-/usr}"
 	USE_BIN=${USE_BIN:-true}
-	DATA_DIR='~/.acdc' # passed verbatim during substitution
+	DEFAULT_LOCAL_PREFIX="${DEFAULT_LOCAL_PREFIX:-~/.local}"
+	DEFAULT_DATA_DIR="${DEFAULT_DATA_DIR:-~/.acdc}"
 else
 	INTERACTIVE=true
 
 	if [ -z "$PREFIX" ]
 	then
-		ask_string "Choose an installation prefix" /usr
+		ask_string "Choose an installation prefix" '/usr'
 		PREFIX="$(eval echo "$ANSWER")"
+
+		mkdir -p "$PREFIX"
 	fi
 
-	if [ -z "$DATA_DIR" ]
+	if [ -z "$DEFAULT_LOCAL_PREFIX" ]
+	then
+		if [ -w "$PREFIX" ]
+		then
+			DEFAULT_LOCAL_PREFIX="$PREFIX"
+		else
+			ask_string "Choose an user-writeable installation prefix" '~/.local'
+			DEFAULT_LOCAL_PREFIX="$(eval echo "$ANSWER")"
+		fi
+	fi
+
+	if [ -z "$DEFAULT_DATA_DIR" ]
 	then
 		ask_string 'Choose a directory for storing data' '~/.acdc'
-		DATA_DIR="$(eval echo "$ANSWER")"
+		DEFAULT_DATA_DIR="$(eval echo "$ANSWER")"
 	fi
 
-	echo -n "Do you want to add an \"acdc\" command? [Y/n] "
-	read -r ANSWER
-	if [[ "$ANSWER" =~ ^([Yy]([Ee][Ss])?)?$ ]]
+	if [ -z "$USE_BIN" ]
 	then
-		USE_BIN=true
-	else
-		USE_BIN=false
+		echo -n "Do you want to add an \"acdc\" command? [Y/n] "
+		read -r ANSWER
+		if [[ "$ANSWER" =~ ^([Yy]([Ee][Ss])?)?$ ]]
+		then
+			USE_BIN=true
+		else
+			USE_BIN=false
+		fi
 	fi
 
 	echo
 fi
 
-REL_INSTALL_DIR="$PREFIX/share/acdc-toolkit"
-INSTALL_DIR="$ROOT$REL_INSTALL_DIR"
+GIT_UPSTREAM_URL="$(git config --get remote.origin.url 2> /dev/null)"
 
 
-# CHECKS
+# Other constants
 
+INSTALL_DIR="$ROOT$PREFIX/share/acdc-toolkit"
+
+
+# Checks
 
 if [ -e "$INSTALL_DIR" ]
 then
@@ -64,22 +89,34 @@ then
 fi
 
 
-# INSTALLATION
+set -e
 
 
-mkdir -p "$INSTALL_DIR"
-cp -r ./. "$INSTALL_DIR"
+# Preparing files
 
-rm -rf "$INSTALL_DIR/packaging" "$INSTALL_DIR"/.git*
-find "$INSTALL_DIR" -type f -exec tools/substitute.sh {} \
-	 'INSTALL_DIR' "$REL_INSTALL_DIR" \
-	 'DATA_DIR' "$DATA_DIR" \;
+BUILD_DIR="$(mktemp -d 2>/dev/null || mktemp -d -t 'acdc-toolkit-dl')"
+
+cp -r ./. "$BUILD_DIR"
+
+maybe_sudo rm -rf "$INSTALL_DIR/packaging" "$INSTALL_DIR"/.git*
+
+find "$BUILD_DIR" -type f -exec tools/substitute.sh {} \
+	 'PREFIX' "$PREFIX" \
+	 'USE_BIN' "$USE_BIN" \
+	 'GIT_UPSTREAM_URL' "$GIT_UPSTREAM_URL" \
+	 'DEFAULT_LOCAL_PREFIX' "$DEFAULT_LOCAL_PREFIX" \
+	 'DEFAULT_DATA_DIR' "$DEFAULT_DATA_DIR" \;
+
+
+# Installation
+
+maybe_sudo mkdir -p "$INSTALL_DIR"
+maybe_sudo cp -r "$BUILD_DIR/." "$INSTALL_DIR"
 
 if $USE_BIN
 then
-	mkdir -p "$ROOT$PREFIX/bin/"
-	cp "$INSTALL_DIR/acdc" "$ROOT$PREFIX/bin/"
-	chmod +x "$ROOT$PREFIX/bin/acdc"
+	maybe_sudo mkdir -p "$ROOT$PREFIX/bin/"
+	maybe_sudo mv "$INSTALL_DIR/acdc" "$ROOT$PREFIX/bin/"
 
 	if $INTERACTIVE && ! grep -q "$ROOT$PREFIX/bin" <<<"$PATH"
 	then
@@ -88,4 +125,7 @@ then
 	fi
 fi
 
-rm "$INSTALL_DIR/acdc"
+
+# Cleanup
+
+rm -rf "$BUILD_DIR"
