feat(install): add message for non-GNU os to ignore sed errors

diff --git a/install b/install
--- a/install
+++ b/install
@@ -74,8 +74,14 @@ else
             USE_BIN=false
         fi
     fi
+fi
 
-    echo
+echo 'Installing...'
+echo ''
+
+if ! man sed | grep GNU; then
+    echo '[WARN] Not a GNU-based operating system.'
+    echo '[INFO] Please ignore all the sed errors.'
 fi
 
 GIT_UPSTREAM_URL="$(git config --get remote.origin.url 2> /dev/null)"
