misc(scripts): fix indentation and replace tabs with 4 spaces

diff --git a/tools/update_toolkit b/tools/update_toolkit
--- a/tools/update_toolkit
+++ b/tools/update_toolkit
@@ -6,26 +6,26 @@
 
 if [ '@_INSTALL_TYPE_@' = 'arch-linux-package' ]
 then
-	if pacman -Si acdc-toolkit > /dev/null 2> /dev/null
-	then
-		echo 'Please just upgrade your system as usual.' >&2
-		exit 1
-	fi
+    if pacman -Si acdc-toolkit > /dev/null 2> /dev/null
+    then
+        echo 'Please just upgrade your system as usual.' >&2
+        exit 1
+    fi
 
-	TMP_DIR="$(mktempdir)"
+    TMP_DIR="$(mktempdir)"
 
-	if git clone --depth=1 'https://gitlab.com/Fiksd/epita-acdc-pkgs.git' "$TMP_DIR"
-	then
-		echo 'Failed to download package.' >&2
-		rmdir "$TMP_DIR"
-		exit 1
-	fi
+    if git clone --depth=1 'https://gitlab.com/Fiksd/epita-acdc-pkgs.git' "$TMP_DIR"
+    then
+        echo 'Failed to download package.' >&2
+        rmdir "$TMP_DIR"
+        exit 1
+    fi
 
-	sudo pacman -U "$(ls -1 "$TMP_DIR/"*.pkg.* | sort -V | tail -n 1)"
-	STATUS=$?
+    sudo pacman -U "$(ls -1 "$TMP_DIR/"*.pkg.* | sort -V | tail -n 1)"
+    STATUS=$?
 
-	rm -rf "$TMP_DIR"
-	exit $STATUS
+    rm -rf "$TMP_DIR"
+    exit $STATUS
 fi
 
 
@@ -34,18 +34,18 @@ fi
 
 if [ '@_INSTALL_TYPE_@' = 'debian-package' ]
 then
-	if git clone --depth=1 'https://gitlab.com/Fiksd/epita-acdc-pkgs.git' "$TMP_DIR"
-	then
-		echo 'Failed to download package.' >&2
-		rmdir "$TMP_DIR"
-		exit 1
-	fi
+    if git clone --depth=1 'https://gitlab.com/Fiksd/epita-acdc-pkgs.git' "$TMP_DIR"
+    then
+        echo 'Failed to download package.' >&2
+        rmdir "$TMP_DIR"
+        exit 1
+    fi
 
-	sudo gdebi "$(ls -1 "$TMP_DIR/"*.deb | sort -V | tail -n 1)"
-	STATUS=$?
+    sudo gdebi "$(ls -1 "$TMP_DIR/"*.deb | sort -V | tail -n 1)"
+    STATUS=$?
 
-	rm -rf "$TMP_DIR"
-	exit $STATUS
+    rm -rf "$TMP_DIR"
+    exit $STATUS
 fi
 
 
@@ -56,9 +56,9 @@ INSTALL_DIR='@_PREFIX_@/share/acdc-toolkit'
 
 if [ -z '@_GIT_UPSTREAM_URL_@' ]
 then
-	echo "The program doesn't seem to have been installed from git." >&2
-	echo "Maybe update it using your package manager." >&2
-	exit 1
+    echo "The program doesn't seem to have been installed from git." >&2
+    echo "Maybe update it using your package manager." >&2
+    exit 1
 fi
 
 
@@ -75,7 +75,7 @@ cd "$DL_DIR"
 NONCE=1
 while [ -e "$INSTALL_DIR.backup.$NONCE" ]
 do
-	((NONCE++))
+    ((NONCE++))
 done
 INSTALL_DIR_BACKUP="$INSTALL_DIR.backup.$NONCE"
 maybe_sudo mv "$INSTALL_DIR" "$INSTALL_DIR_BACKUP" || exit 1
@@ -84,21 +84,21 @@ maybe_sudo mv "$INSTALL_DIR" "$INSTALL_DIR_BACKUP" || exit 1
 # Reinstalling
 
 INTERACTIVE=false \
-		   PREFIX='@_PREFIX_@' \
-		   USE_BIN='@_USE_BIN_@' \
-		   GIT_UPSTREAM_URL='@_GIT_UPSTREAM_URL_@' \
-		   DEFAULT_LOCAL_PREFIX='@_DEFAULT_LOCAL_PREFIX_@' \
-		   DEFAULT_DATA_DIR='@_DEFAULT_DATA_DIR_@' \
-		   ./install
+           PREFIX='@_PREFIX_@' \
+           USE_BIN='@_USE_BIN_@' \
+           GIT_UPSTREAM_URL='@_GIT_UPSTREAM_URL_@' \
+           DEFAULT_LOCAL_PREFIX='@_DEFAULT_LOCAL_PREFIX_@' \
+           DEFAULT_DATA_DIR='@_DEFAULT_DATA_DIR_@' \
+           ./install
 
 STATUS=$?
 if [ $STATUS -ne 0 ]
 then
-	echo 'Failed to install new version. Restoring old one.' >&2
-	maybe_sudo rm -rf "$INSTALL_DIR"
-	maybe_sudo mv "$INSTALL_DIR_BACKUP" "$INSTALL_DIR"
+    echo 'Failed to install new version. Restoring old one.' >&2
+    maybe_sudo rm -rf "$INSTALL_DIR"
+    maybe_sudo mv "$INSTALL_DIR_BACKUP" "$INSTALL_DIR"
 else
-	maybe_sudo rm -rf "$INSTALL_DIR_BACKUP"
+    maybe_sudo rm -rf "$INSTALL_DIR_BACKUP"
 fi
 
 
